### ISSUE TITLE
Git LFS Quota reached

### ISSUE THREAD

**Issue by MarvinJWendt** [motion-canvas/examples#3]
Hi, the repository is currently not cloneable, as the GitHub Git LFS quota has been reached: `This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

There are some solutions that I could think of:

1. Increase the Git LFS quota (this is obviously connected to real costs, which is always a struggle for open source projects - every 50 GB of download / storage is $5 per month)
2. Create releases for major updates and append the full project as a zip in the release assets.
3. Upload the full project to a web hosting service (or a Dropbox / Google Drive / etc. link)

Thanks for open sourcing this awesome project ❤️  

---

### Workaround

A workaround, [posted](https://github.com/motion-canvas/examples/issues/3#issuecomment-1442579061) by @m-roberts, is to download the zip from [here](https://github.com/motion-canvas/examples/files/10819361/motion-canvas-examples-master.zip).

**Comment by paulmiu** [comment]
I'm happy to cover the costs as a donation to the project.

**Comment by m-roberts** [comment]
+1 for Releases

**Comment by codeSTACKr** [comment]
+1 for releases

**Comment by paulmiu** [comment]
**For all impatient people like me:**

I used this StackOverflow answer as a workaround for now: https://stackoverflow.com/a/68113604/2524925

But I agree, releases with all assets are probably the right way to do it.

**Comment by fuhadabdulla** [comment]
> 

Thank you mamiu , i got it working because of your answer . I am not able view the deffered lighting animation in the browser . code run successfully but i am not able play it . is it because my pc is not powerful . i was  able to play other examples.

![image](https://user-images.githubusercontent.com/68536959/219842704-d8d0a1cd-4a84-4a0c-8508-45732c049cca.png)

**Comment by m-roberts** [comment]
> **For all impatient people like me:**
> 
> I used this StackOverflow answer as a workaround for now: https://stackoverflow.com/a/68113604/2524925
> 
> But I agree, releases with all assets are probably the right way to do it.

For **even more impatient people** (anyone who would like to avoid forking), [here](https://github.com/motion-canvas/examples/files/10819361/motion-canvas-examples-master.zip) is a zip for the project ([#21587b4](https://github.com/motion-canvas/examples/commit/21587b445439f482f0974196b38a2c041998c8bb)).

**Comment by aarthificial** [comment]
Hi everyone!

Apologies, I forgot to check the issues in this repo.
Since all assets here are really small (the largest are the audio files which are still < 10MB) and they rarely change, I think it may be easier to just disable LFS for this repo and store them as normal files.

What do you think about this?

**Comment by MarvinJWendt** [comment]
Hi @aarthificial, I think it's fine, since the assets are rarely if ever updated, git shouldn't have any problems here.

**Comment by aarthificial** [comment]
LFS has been removed in #9
